resources:
  - sa-data-on-eks.yaml
  - sa-tf-eks-observability.yaml
  - cluster-workflow-data-on-eks.yaml
  - cluster-workflow-data-on-eks-cleanup.yaml
  - cluster-workflow-spark-rbac.yaml
  - cluster-workflow-tf-eks-observability.yaml
  - cluster-workflow-tf-eks-observability-cleanup.yaml
  - sa-backstage-scaffolder.yaml
