apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: jupyterhub-on-eks-${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    backstage-id: eks-cluster-${{values.name}}
    entity-id: ${{values.name}}
    env: dev
spec:
  arguments:
    parameters:
      - name: backstage-entity-name
        value: eks-cluster-${{values.name}}
      - name: script-location
        value: ai-ml/jupyterhub
      - name: admin-role
        value: ${{values.adminRoleName}}
  workflowTemplateRef:
    name: terraform-data-on-eks
    clusterScope: true
